language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - 'python3 setup.py install'
script:
  - 'python3 -m doctest cube_scramble_cli/scramble_cli.py'
